### ISSUE TITLE
mb_bios_x670-ae-ax-f4.zip

### ISSUE THREAD

**Issue by halcy** [bmgjet/-X670-AORUS-ELITE-AX-Bios#1]
This repo is amazing, especially since Gigabyte wiped most of the bios files off their website for compatibility reasons! I see that bios version F4 for the x670 Elite AX is currently not in there - any chance you might have it somewhere? It was the one version that actually ran stably on my machine (F3 might work too, I will probably try that later today).

In any case - thank you so much!

**Comment by bmgjet** [comment]
Sadly I don't these are just the ones I had on my HDD.
Personally F5 is the best bios for me.
F3 had issues with settings not applying. And F6 to F9 all had hot restarting issues.
